### ISSUE TITLE
Milestone 1 - DB schema

### ISSUE THREAD

**Issue by i-norden** [vulcanize/filecoin-indexing#1]
- [ ] Review existing database and IPLD schemas.

- [ ] Modify existing Lily database schema where necessary.

- [ ] New table definitions/migrations for HAMT nodes and actor state.

- [ ] New table definition/migration for internalized IPLD blockstore.

- [ ] Adjust table definitions so that models reference IPLD blocks in the internal blockstore.

- [ ] Basic documentation and UML diagrams.
