### ISSUE TITLE
Milestone 2 - Filecoin chain and state extractors

### ISSUE THREAD

**Issue by i-norden** [vulcanize/filecoin-indexing#2]
- [ ] Implement individual chain and state extractors for Filecoin data.
    * Based on fil-fip36-vote-tally parse state code.
    * ADT node/actor model extractor.
    * Chain model extractors.
    * Define and expose generic block stream interface.
    * Supports two modes - realtime and historical - that can be configured with the appropriate data source (streaming data from a live node or reading data from an offline database)
- [ ] Implement snapshotting service.
    * Uses a state extractor that processes the entire state at a given height, not just the differential set between two states.
    * This state extractor is essentially the fil-fip36-vote-tally parse state code that has been modified to process internal nodes. Also analogous to our ipld-eth-state-snapshot tool.
- [ ] Unit and integration testing.
- [ ] Basic documentation.
