### ISSUE TITLE
Milestone 3 - IPLD block stream indexers

### ISSUE THREAD

**Issue by i-norden** [vulcanize/filecoin-indexing#3]
- [ ] Implement stock Filecoin indexers that target a relational database schema inspired by Lily database (see Milestone 1).
    * Designed to support any type of relational database and database drivers in the future.
    * Can be configured with different schemas.
    * Can optionally output statements as .sql or .csv files or write directly over a database connection.
- [ ] Implement coordination service.
    * Composes and coordinates extractors and indexers over select subsets (or the entire set) of Filecoin data.
    * Can coordinate historical and realtime processing. 
    * Potentially handled entirely by a docker-compose.
- [ ] Unit and integration testing.
- [ ] Basic documentation.
