### ISSUE TITLE
Epic - Filecoin indexing and cacheing tooling

### ISSUE THREAD

**Issue by i-norden** [vulcanize/filecoin-indexing#4]
- [ ] Database table definitions (migration files and resultant schema.sql). #1
- [ ] Source code and dockerfile for modified Lotus node that supports extracting state data in a differential format. #2, #3
- [ ] Source code and dockerfiles for chain and state extractors. #2
- [ ] Source code and dockerfiles for chain and state indexers that target the database definitions defined in (1). #3
- [ ] Docker-compose and scripts for configuring and coordinating the composition of the above processes. #3
    * Required user input should be minimal: URL or path for live and/or offline data source(s) (node RPC endpoint or database file location); parameters to define which subsets of the chain to process; URL or path for data destination.
